sudo: required

language: python

python:
  - "2.7"

services:
  - docker

branches:
  only:
   - oxa/master.fic
   - oxa/dev.fic

# command to install dependencies
# Note: Keep this to avoid "Could not locate requirements.txt.  Override the install: key in your .travis.yml to install dependencies"
install:
  - bash ./scripts/travis-install.sh

before_install:
  # Login and fetch container from Azure container registry
  - docker login oxacontainerregistry.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull oxacontainerregistry.azurecr.io/ci/devstack
  - docker run -d --name devstack --add-host "localhost preview.localhost":127.0.0.1 --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t oxacontainerregistry.azurecr.io/ci/devstack
  - docker ps -a
  # Prepare cgroup on the host at /tmp/cgroup to avoid error: "failed to connect to bus: no such file or directory"
  - sudo mkdir -p /tmp/cgroup/systemd && sudo mount -t cgroup systemd /tmp/cgroup/systemd -o ro,noexec,nosuid,nodev,none,name=systemd

# command to run tests
script: ./scripts/travis-tests.sh

dist: trusty
